### ISSUE TITLE
Unable to access Tide's Jar to attach session information?

### ISSUE THREAD

**Issue by phated** [http-rs/async-session#1]
I've been diving into session management in Tide. It seems like it is still a WIP but it sounded like this library is the direction things are moving towards.

I am noticing that Tide's cookie middleware hides the CookieJar from the consumer, so it can't be used with these traits. I'm not sure whether Tide should allow access to the CookieJar or if this should be changed to take a Request/Response pair instead of a CookieJar.

Any thoughts?

**Comment by jbr** [comment]
This was in fact the biggest challenge in implementing tide sessions with the old api. Closing this issue as it has now been addressed

**Comment by phated** [comment]
@jbr can you link where this was addressed? I'm trying to keep up on things but I didn't see this.

**Comment by jbr** [comment]
Check out #2 and https://github.com/http-rs/tide/pull/646
