### ISSUE TITLE
Session API requirements for Privilege-Level Changes, based on OWASP recommendations

### ISSUE THREAD

**Issue by Dowwie** [http-rs/async-session#11]
A few features are missing from the Session api:

1. session key renewal
2. session purge

**1. Session key renewal**
Two of the most common events in a web application where there are "privilege-level changes" are login and logout, but [there are others](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#renew-the-session-id-after-any-privilege-level-change).  Each of these events requires the Session ID be renewed.  With this given, the Session API requires renewal functionality so that one may renew the session key on-demand.  Although the Session ID changes, state is preserved.

**2. Session purge**
Purging involves removing the session state AND the cookie (ie "purge").  Purging is done during the logout process, for instance.

If you'd like to see an example implementation, such functionality exists [in actix-web]( https://github.com/actix/actix-extras/blob/master/actix-session/src/lib.rs#L176) and an example useful for integration testing [can be found here](https://github.com/actix/examples/blob/master/redis-session/src/main.rs).

**Comment by jbr** [comment]
Purge exists and is currently called destroy. The destroy flag on session is used by the tide session middleware to delete the session from the backing store and remove the cookie: https://github.com/http-rs/tide/blob/master/examples/sessions.rs#L32

Session key renewal is called `Session::regenerate`.

Let me know if there's something missing from either of these, or if the naming is unclear. There's a lot to get right in sessions and I wouldn't be at all surprised if there were bugs or missing features

**Comment by jbr** [comment]
@Dowwie Are the names you used (purge vs destroy, renew vs regenerate) standardized enough that you think it's worth changing the API?

**Comment by Dowwie** [comment]
They were the best that I could come up with.  I'm not aware of any standard.  I think that regenerate and destroy are fine!

**Comment by jbr** [comment]
Closing this issue then, but please do keep reporting shortcomings you find!
