### ISSUE TITLE
PostgresStore

### ISSUE THREAD

**Issue by phungtranminh** [http-rs/async-session#19]
Hi I am writing a PostgresStore for this, I wonder if I just dump the whole session into Postgres or there are more preferable approach?

Something like this:

```
serde_json::to_string(&session).ok()
```

**Comment by jbr** [comment]
take a look at https://github.com/jbr/async-sqlx-session, and I recommend copying over the test suite and making the minimum-necessary modification to ensure compatibility and security

**Comment by phungtranminh** [comment]
Right thanks, didn't see it earlier, I will probably just use the library directly.
