### ISSUE TITLE
What does calling destroy on Session do?

### ISSUE THREAD

**Issue by lambdagolem** [http-rs/async-session#29]
Reading the code i couldn't figure out what calling `Session::destroy` really does. The documentation currently reads:
> mark this session for destruction. the actual session record is not destroyed until the end of this response cycle.

From my quick reading of the code I didn't find find any location in the code where the destroy flag is read and the Session is actually destroyed.

**Comment by jbr** [comment]
https://github.com/http-rs/tide/blob/main/src/sessions/middleware.rs#L99-L108

**Comment by lambdagolem** [comment]
Thank you for your response. That makes a lot of sense. I stubled over `async-session` in the example code of `axum` (https://github.com/tokio-rs/axum/blob/main/examples/sessions/src/main.rs) where only an incomplete implementation exists.
