### ISSUE TITLE
Status of this crate?

### ISSUE THREAD

**Issue by maxcountryman** [http-rs/async-session#46]
Hi folks, it looks like the last published release was in May of 2021.

I'm curious if the maintainers could let us know if we should expect future releases or if projects utilizing this crate should instead publish their own releases?

**Comment by jbr** [comment]
Yes this crate is maintained. It is not expected to be a high churn crate, so infrequent releases are a feature not a flaw. Please open issues if there are specific changes you'd like to make

**Comment by maxcountryman** [comment]
#14 has been open for two years. Will that be merged or should we fork instead?

**Comment by jbr** [comment]
I will happily merge #14 if it's important to you, but I do not believe the behavior that the PR guards against to be reachable, which is why it stayed unmerged for so long.

**Comment by jbr** [comment]
14 is merged. I will publish v4 soon, incorporating all changes since the last release (some of which were breaking).

**Comment by maxcountryman** [comment]
Great. Given that there's been a backlog of pending changes, do you anticipate releases will be more common in the future if a similar situation arises? I guess I'm a bit confused about what it means for it to be a feature that there aren't releases when there are unreleased changes on the mainline.

**Comment by jbr** [comment]
It depends on what the changes are. This interface is fairly mature and hopefully will not require frequent breaking changes. What do you have in mind? I'm happy to release semver-minor/semver-patch changes as often as needed.

In general, if you have a business that depends on this software, sponsor me and I will be able to prioritize my open source work higher.

**Comment by maxcountryman** [comment]
This isn't for commercial use (or if it is, it's not to my benefit: I do not run a business which uses this crate directly or indirectly or otherwise make money from it).

I've authored crates which use this crate and so my community's interest is in understanding the foundations those crates are built on. (I don't think monetary compensation is possible but I'd be happy to donate my time as I've said before.)

I also would like to say that I'm not asking you to do any work that you wouldn't otherwise do (or any work at all for that matter): I'm only trying to understand what the commitment to maintenance is or isn't so that my crates can make an informed decision about how to proceed.
